### ISSUE TITLE
Use globbing in container name

### ISSUE THREAD

**Issue by kallekutta** [timdaman/check_docker#1]
Hello,

I'm sorry in advance if it is me who doing something wrong but there is one thing I can't get to work. I'm checking a container to see if it is running. This is the command:

/home/nagios/plugins/check_docker.py --containers container_version_1 --status running

Everything works fine until I do some updates to the container and change the name to container_version_**2**. Then obviously the alarm will go off because the name is different. Changing names is something I need to do so I tried this command:

/home/nagios/plugins/check_docker.py --containers container_version_* --status running

But it doesn't work. Can this be fixed in some way? Or is it me who is using the wildcard in the wrong way?

**Comment by timdaman** [comment]
Pardon the delay, I have been travelling. 

Hmm, interesting idea. The asterisk would be a bit messy as it could be interpreted by the shell but perhaps could add a --prefix or --substring switch?

I will think about it for a little while and see works best.

**Comment by kallekutta** [comment]
I have created my own script which supports globbing. So I don't use this anymore, sorry.

**Comment by timdaman** [comment]
No worries, thanks for the suggestion though, it will certainly make a good feature.

**Comment by timdaman** [comment]
I just merged regex support.
