### ISSUE TITLE
Wrong shebang on pypi

### ISSUE THREAD

**Issue by tatref** [timdaman/check_docker#16]
The version on `pip` has a wrong shebang:

```
# check_docker
-bash: /root/Python-3.6.1/.venv/bin/check_docker: /usr/local/bin/python3.6: bad interpreter: No such file or directory
```
```
# head -1 $(which check_docker)
#!/usr/local/bin/python3.6
```

This is different than the version on github.
Can you publish a new version?

Thanks!

**Comment by timdaman** [comment]
I think this is a execution environment issue. not a package issue. Does the behavior described in the link below look like what you are seeing?
https://docs.python.org/3/distutils/setupscript.html#installing-scripts

**Comment by tatref** [comment]
I'm not sure.

I compiled python 3.6 from source + created a virtualenv with my freshly compiled python like so:
```

./python -m virtualenv venv
. ./venv/bin/activate
pip install check_docker
```

Other packages have the correct interpreter:

```
pip install grip
head -1 $(which grip)
#!/root/Python-3.6.1./.venv/bin/python
```

I will try to dig into this.

**Comment by timdaman** [comment]
I am going to close this as I cannot recreate the issue and it has been a while. Reopen if you still are having trouble.
