### ISSUE TITLE
Base 1000 or 1024 units?

### ISSUE THREAD

**Issue by timdaman** [timdaman/check_docker#28]
This a place to discuss units used to be used when processing and returning performance data. 

The basic question is  1KB = 1000B or 1KB = 1024B? The Nagios Ecosystem does not make this clear. 

According to wikipedia the '1000' base should be used with KB
https://en.wikipedia.org/wiki/Kilobyte

But looking at the actual code for the 'offical' nagios plug-ins they appear to consistantly use a base of '1024'. Best examples are `check_disk` and `check_swap`
https://github.com/nagios-plugins/nagios-plugins/search?utf8=%E2%9C%93&q=1024&type=

To add more fuel to the fire I see code in pnp4nagios that looks to use base 1000.

I am inclined to go for 1024 as that seems to be what the Nagios folks intended the meaning to be but I would love to hear other points of view.

**Comment by tatref** [comment]
Thanks for opening the question!

Some arguments for 1024 = KiB / 1000 = KB:

* `docker stats` uses MiB/GiB units
* the json stats are in bytes
* pnp4nagios has helper function to convert to 1000 or 1024 basis: https://docs.pnp4nagios.org/pnp-0.6/tpl_helper_pnp, so the conversions can be defered to the frontend (keep perfdata in B)
* there was some discussion about the disk checks yielding wrong units here: https://sourceforge.net/p/pnp4nagios/mailman/message/15564564/
* misleading units lead to bigger and bigger differences between 1000 and 1024-base measures: https://en.wikipedia.org/wiki/Binary_prefix#Deviation_between_powers_of_1024_and_powers_of_1000
* extreme example of confusion between units: the "1.44 MB" floppy disks holds 1.44 * 1000 * 1024 bytes

**Comment by timdaman** [comment]
Neat one, I didn't know that about floppies. Ugh. 

I don't think what base docker uses is important, it is all about how it is displayed by the tools the user is using (nagions/incinga/etc).

I just pushed an update to the `prep_for_v2` branch and that may be a good comprise. By default it uses base 1024 but '--decimal_units' switches that to 1000. What do you think? Also, does the help text make sense to you?

**Comment by tatref** [comment]
This is great! The text seems clear to me also :-)

**Comment by timdaman** [comment]
FYI, I just merged v2.0.0 into master. I am going to wait a day before pushing to pypi to give bugs a chance to bubble up.
Thanks for your observations and help.

**Comment by timdaman** [comment]
I am closing this issue as I have pushed the release that addresses this to pypi.
