### ISSUE TITLE
Icinga graphite writer perfdata error

### ISSUE THREAD

**Issue by serverbiz** [timdaman/check_docker#29]
Using this check on icinga2 with the GraphiteWriter plugin results in a "Ignoring invalid perfdata value" warning from GraphiteWriter. This is because the performance data output does not comply with the [official standard](https://www.monitoring-plugins.org/doc/guidelines.html#AEN201), which dictates that no unit of measurement should be specified. The check_docker output does specify a unit for the memory performance data.

**Comment by timdaman** [comment]
Do this look like the issue mentioned here?
    https://github.com/timdaman/check_docker/pull/22
What version of the plug-in are you using? It is listed near the top of the file.

I am just finishing a new release of the plug-in that corrects the problem mentioned in the PR above. If you are able could you try out the new release and tell me if it looks like it resolved your issue as well?
   https://github.com/timdaman/check_docker/raw/prep_for_v2/check_docker

**Comment by serverbiz** [comment]
Yes I do apologize. I misinterpreted that PR, but it seems to be the same issue.

Tested your v2 and it seems to work perfectly. Finally getting graphite graphs in icinga2 for docker checks!

**Comment by timdaman** [comment]
FYI, I just merged v2.0.0 into master. I am going to wait a day before pushing to pypi to give bugs a chance to bubble up.
Thanks for you help getting this polished.
