### ISSUE TITLE
Monitor age

### ISSUE THREAD

**Issue by KristianLyng** [timdaman/check_docker#3]
It's frequently nice to get an alert if a service has (presumably unexpectedly) restarted.

Something along the lines of «./check_docker --containers foobar --status running --age 600:60» could work, indicating a warning if the age is less than 600 seconds and a critical if it's less than 60 seconds. Critical needs to be optional, though (don't want to wake people up if it's back up).

**Comment by timdaman** [comment]
I just want to make sure I understand, are you thinking that we could monitor for services that don't stay up but if they crash infrequently that is OK? 

Combining that with a requirement of two or more failures before alerting could come in very handy.

**Comment by KristianLyng** [comment]
Your idea makes some sense, but wasn't what I originally thought of.

Basically, if a service restarts, I want an alert. There are two ways of doing this: watch for the actual event, or check if uptime is lower than some interval. 

This is basically the shell script implementation (minus return codes and actual sanity):
```
kly@leia:~$ docker inspect gondul-db-test | sed 's/[",]//g' | awk 'BEGIN { "date +%s" | getline real } /StartedAt/ { "date +%s --date " $2 | getline start;}  END { uptime=(real - start); if (uptime < 600) printf "CRITICAL: "; else if (uptime < 1800) printf "WARNING: "; else printf "OK: "; printf "Uptime: %s seconds\n", uptime;}' 
CRITICAL: Uptime: 535 seconds
kly@leia:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
8aa3bb0bd9ce        gondul-db-test      "/bin/sh -c 'pg_ctlcl"   12 days ago         Up 9 minutes        5432/tcp            gondul-db-test
```

**Comment by KristianLyng** [comment]
A counter for acceptable restarts could also be neat, but sounds a lot trickier. Just watching the uptime is nice if you have a few hundred servers and services should "always" be up. Even if they start back up again, a n unexpected restart would be reason for further investigation.

**Comment by timdaman** [comment]
There already is monitoring for restarts with the --restarts flag. I still am interested in merging age monitoring though.

**Comment by timdaman** [comment]
FYI, I merged functionality to monitor container age, aka "uptime".
