### ISSUE TITLE
ImportError: No module named machinery

### ISSUE THREAD

**Issue by magarciasopo** [timdaman/check_docker#33]
Hello, 

I have problems to install this plugin. I follow the instructions:

> pip install check_docker

python version: Python 2.7.12

the output is:

>   Downloading check_docker-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9FnbpP/check-docker/setup.py", line 3, in <module>
        from importlib.machinery import SourceFileLoader
    ImportError: No module named machinery

I tried to install all versions but I got the previous error or     check_docker requires Python 3.3 or higher.

Can I install this plugin along with python 2.7.12??

Cheers!

**Comment by kabir1995** [comment]
hi 
did you solve this problem ?
I am also having the same problem.

**Comment by timdaman** [comment]
The original poster closed it before I had a chance to reply but the description implies they were using Python version 2.7. check_docker only supported 3.3 and above at the time.

At this point I have followed the Python 3.3 deprecation and ceased to test with it as well. That does not mean check_docker will not work on 3.4 or earlier, likely it will still work. I just don't test and support check_docker on versions of Python earlier than 3.4.
