### ISSUE TITLE
Comment does not appear in Icinga

### ISSUE THREAD

**Issue by magarciasopo** [timdaman/check_docker#35]
Hello, 

I'm running the scripts along with nagios command: 

/opt/nagios-check ' python /opt/checks/check_docker --containers <container_name> --health ' <passive alarm name>

It seems all ok, however the output message it's written in console but it's not written to icinga alarm. How do you recommend me to run the check?

Cheers

**Comment by timdaman** [comment]
Hmm, I must say I find that surprising. I will check the plugin doc and see if i have missed anything.

I notice you are running `python ...`. Are you sure the python in the search path for Nagios is python version 3.3 or greater? Do you have a a `python3` command? That would make it clear which version was being called by Nagios.

**Comment by timdaman** [comment]
I took a peek at the doc and it looks like output to 'stderr' is not processed by Nagios so my current there is there  some sort of 'environment' problem you are seeing.

The code has a wrapper that catches and converts all the errors and sends them to 'stdout' so coding errors should be obvious. The leaves errors generated by other things like the python environment or the OS as the prime suspects.

**Comment by timdaman** [comment]
Closing this due to lack of replies. Feel free to reopen if you are still having issues.
