### ISSUE TITLE
Health Check not working

### ISSUE THREAD

**Issue by alexeightsix** [timdaman/check_docker#57]
If I do:

usr/lib64/nagios/plugins/check_docker --container='container' --status health it says 

CRITICAL: container state is not health

While If i do:

docker inspect -f '{{json .State.Health.Status}}' container

It says "healthy"

Docker version 18.09.1, build 4c52b90

**Comment by timdaman** [comment]
Ah, I see. I think you might be confused. Containers have  a bunch of state vars. One basic type is `status` which in concerned about if the container is running, restart, etc. Another is `health`. That runs the command specified by the `HEALTHCHECK` option in a Dockerfile and records the results. For example the web-server could have a status of`running` but when the API it is offering is hit there are errors returned. Status would be running and health would be unhealthy.

If you want to check health use the `--heath` check. 

If you want to make sure your container is running but you don't want to check if it is healthy then `--status running` is what your after.

**Comment by timdaman** [comment]
Closing.
