### ISSUE TITLE
Error when running status

### ISSUE THREAD

**Issue by Carlospi99** [timdaman/check_docker#6]
Hi guys,

 have a error when running  the check;
./check_docker.py --containers mycontainer --status running
UNKNOWN: Exception raised during check: KeyError('Status',)

I have Python 3.4.0.

have you had this before?

Thanks

**Comment by timdaman** [comment]
I have to run off to work but I took a quick look. I am testing on 3.4 but there may gaps in the test. One question, what version of docker are you running?

**Comment by timdaman** [comment]
Could you send me the output of this command. I think that is the data it is erroring out on.

`docker inspect --format='{{json .State}}' mycontainer`

**Comment by Carlospi99** [comment]
Hi Tim,

Sorry for the late respond. I have a Busy day.

Docker version 1.5

..
the output is  
{"Error":"","ExitCode":0,"FinishedAt":"2017-03-02T02:07:19.462561847Z","OOMKilled":false,"Paused":false,"Pid":21384,"Restarting":false,"Running":true,"StartedAt":"2017-03-02T02:08:02.996306677Z"}

**Comment by timdaman** [comment]
A-ha. I see the cause. Looks like the API was changed sometime after 1.5. I am running 1.13 and I get output that looks like this.

{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":8734,"ExitCode":0,"Error":"","StartedAt":"2017-02-16T09:59:03.97098259Z","FinishedAt":"0001-01-01T00:00:00Z"}

I will have to think about this a bit. That data structure conflicts with the method I am a using to compare status on newer installs. 

There is probably a reason you are using 1.5 I think updating will take of the issue.

**Comment by Carlospi99** [comment]
HI Tim,

Thank you for you time looking into the issue. The reason I am using 1.5 is due the stack I am working at the moment. I have to test the new versions of docker with the current containers first.

**Comment by timdaman** [comment]
I think I have a  fix. It is a bit hacky but it should work reliably if you are just trying to ensure your containers are running. Give it a try and let me know what you think.

**Comment by Carlospi99** [comment]
HI Tim,

Thank you very much , I tested and it s running fine for status.
