### ISSUE TITLE
CRITICAL: debian's version does not match registry

### ISSUE THREAD

**Issue by Al2Klimov** [timdaman/check_docker#65]
... but it actually matches.

How to reproduce:

1. Provision a new VM as show below
2. Wait a few days so there's a new version of the Docker image `debian:testing-slim`
3. In `/dc`
    1. `docker-compose down`
    2. `docker pull debian:testing-slim`
    3. `docker-compose pull debian` (just to be sure)
    4. `docker-compose up -d --force-recreate`
4. Wait a few seconds
5. `check_docker --version`

```ruby
def mkVm (config, hostname, box, script)
  config.vm.define hostname do |cfg|
    cfg.vm.box = box
    cfg.vm.hostname = hostname

    cfg.vm.synced_folder ".", "/vagrant"
    cfg.vm.network "private_network", type: "dhcp"

    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    cfg.vm.provision "shell", inline: script
  end
end

Vagrant.configure("2") do |config|
  mkVm config, "dc", "debian/contrib-buster64", <<-SHELL
sudo bash -exo pipefail <<BASH

apt-get install -y wget python3-pip
wget -O- https://download.docker.com/linux/debian/gpg |apt-key add -

cat <<REPO >/etc/apt/sources.list.d/docker.list
deb https://download.docker.com/linux/debian buster stable
REPO

apt-get update
apt-get install -y docker-ce docker-compose

pip3 install check_docker

mkdir /dc
cd /dc

cat <<YML >docker-compose.yml
version: '2.4'
networks:
  host-debian:
    internal: true
    driver_opts:
      com.docker.network.bridge.name: docker1
    ipam:
      config:
      - subnet: 192.168.234.0/30
        gateway: 192.168.234.1
services:
  debian:
    container_name: debian
    image: debian:testing-slim
    command:
    - bash
    - -exo
    - pipefail
    - -c
    - |-
      while sleep 86400; do true; done
    restart: always
    networks:
      host-debian:
        ipv4_address: 192.168.234.2
YML

/usr/bin/docker-compose up -d --force-recreate

BASH
SHELL
end
```

**Comment by timdaman** [comment]
Thank you for the report. The next few weeks are pretty busy for me but I am I already fixing something in the Swarm code so I will see if I can look at this at the same time.

What I am noticing is my test suites are also failing when they passed previously. I think the Docker Hub may have made a change. I did a bit digging last night and I can recreate the issue so hopefully it won't be too much work to resolve.

**Comment by timdaman** [comment]
I believe version 2.2.1 should resolve this issue. Let me know if you see otherwise.

**Comment by Al2Klimov** [comment]
Version 2.2.1 of what? (https://github.com/timdaman/check_docker/tags)

**Comment by timdaman** [comment]
`pip install check-docker==2.2.1`

You can also snag the check_docker.py from the master branch which is currently sitting at 2.2.1
https://github.com/timdaman/check_docker/blob/master/check_docker/check_docker.py

**Comment by Al2Klimov** [comment]
Purrs like a cat, thanks.
