### ISSUE TITLE
containers_runnings not detecting running containers

### ISSUE THREAD

**Issue by werebear73** [timdaman/check_docker#68]
I been trying to work through is for just monitoring the particular containers that I want when I realized that it was detecting any as running.  Over half of the host are running, but the check says 0 are running.  Am I doing something wrong with my command?

[nagios@hostname ~]$ /usr/local/nagios/libexec/check_docker.py -H http://127.0.0.1:2375 --check-type 'containers_running' --all -t 0 -l -w '50:' -c '30:'
CRITICAL: 0 running, 11 not running, containers not running: ['/host01', '/host02', '/host03', '/host04', '/host05', '/host06', '/host07', '/host08', '/host09', '/host10', '/host11'] | total_usage=0;50:;30:

**Comment by timdaman** [comment]
Sorry, I think you may be looking at the wrong project. My `check_docker` command does not accept any of those arguments. 

Are you looking for some other project that is using the "check_docker" name?

**Comment by werebear73** [comment]
Sorry, I will see if I can find it.
